export interface DefaultWorksheet {
  "Carimbo de data/hora": string;
  CNPJ: string;
  "Nome fantasia da empresa": string;
  "Razão social da empresa": string;
  "Ano de fundação": string;
  "CNAE (Classificação Nacional de Atividades Econômicas) da empresa": string;
  "Telefone comercial": string;
  "Email institucional": string;
  "Endereço da empresa": string;
  Bairro: string;
  Cidade: string;
  Estado: string;
  CEP: string;
  "Insira uma breve descrição da empresa": string;
  "Liste os principais produtos e/ou serviços oferecidos, separando-os por ; (ponto e vírgula)": string;
  "Caso a sua empresa atue no desenvolvimento de tecnologias, indique as 5 principais tecnologias desenvolvidas pela mesma separadas por ; (ponto e vírgula)": string;
  "Logotipo da empresa": string;
  "Site da empresa": string;
  "A empresa está ou esteve em alguma incubadora ou Parque tecnológico?": string;
  "Em qual incubadora ou Parque Tecnológico?": string;
  "Unicórnio?": string;
  "Número total de colaboradores": string;
  "Links para as redes sociais da empresa": string;
  "Sua empresa gostaria de receber o selo DNA USP?": string;
  "Por qual email podemos entrar em contato para tratar do uso da marca DNA USP?": string;
  "Qual o nome do responsável por este email?": string;
  "Contrato para uso da marca DNA USP (enviado ou assinado) - informações da planilha: https://docs.google.com/spreadsheets/d/1LgHUJQh-lYSP03owr6Uhb0kSyWsu0tsNUwfnpu9UKJw": string;
  "Declaro que as informações fornecidas são verdadeiras e que a empresa atende aos critérios estabelecidos": string;
  "Selecione as opções com as quais a empresa está de acordo": string;
  "Nome completo do empreendedor que possuiu ou mantém vínculo com a USP (sem abreviações) (Sócio 1)": string;
  "Número USP (Sócio 1)": string;
  "Qual tipo de vínculo já possuiu ou ainda mantém com a USP?": string;
  "Com qual instituto, escola ou centro é o vínculo atual ou mais recente?": string;
  Cargo: string;
  "Email do empreendedor": string;
  "Telefone (fixo ou celular)": string;
  "Quantos sócios a empresa possui?": string;
  "Possui sócios que mantiveram ou mantêm vínculo com a USP?": string;
  "Gostaria de adicionar os dados dos demais sócios?": string;
  "Nome completo (Sócio 2)": string;
  "Número USP (Sócio 2)": string;
  "Qual o tipo de vínculo possuiu ou mantém com a USP (Sócio 2)?": string;
  "Com qual instituto, escola ou centro é o vínculo atual ou mais recente?__1": string;
  "Deseja adicionar os dados de outro sócio?": string;
  "Nome completo (Sócio 3)": string;
  "Número USP (Sócio 3)": string;
  "Qual o tipo de vínculo possuiu ou mantém com a USP (Sócio 3)?": string;
  "Com qual instituto, escola ou centro é o vínculo atual ou mais recente?__2": string;
  "Deseja adicionar os dados de outro sócio?__1": string;
  "Nome completo (Sócio 4)": string;
  "Número USP (Sócio 4)": string;
  "Qual o tipo de vínculo possuiu ou mantém com a USP (Sócio 4)?": string;
  "Com qual instituto, escola ou centro é o vínculo atual ou mais recente?__3": string;
  "Deseja adicionar os dados de outro sócio?__2": string;
  "Nome completo (Sócio 5)": string;
  "Número USP (Sócio 5)": string;
  "Qual o tipo de vínculo possuiu ou mantém com a USP (Sócio 5)?": string;
  "Com qual instituto, escola ou centro é o vínculo atual ou mais recente?__4": string;
  "Qual o número de funcionários contratados como CLT?": string;
  "Qual o número de colaboradores contratados como pessoa jurídica (PJ)?": string;
  "Qual o número de estagiários/bolsistas contratados?": string;
  "A empresa recebeu investimento?": string;
  "Qual(is) investimento(s) a empresa recebeu?": string;
  "Valor do investimento próprio (R$)": string;
  "Valor do investimento-anjo (R$)": string;
  "Valor do Venture Capital (R$)": string;
  "Valor do Private Equity (R$)": string;
  "Valor do PIPE-FAPESP (R$)": string;
  "Outros investimentos (R$)": string;
  "Qual foi o faturamento da empresa em 2020? (R$)": string;
  "Porte (RFB)": string;
  "Faturamento 2019 (ou estimativa da RFB) com porte": string;
  "Faturamento 2018 (RFB)": string;
  "Nº colaboradores (RAIS 2015 )": string;
  "Nº sócios (RAIS 2018 )": string;
  "Nº colaboradores (RAIS 2018 )": string;
  "Nº colaboradores (RAIS 2019 )": string;
  "Somatório RAIS 2018": string;
  "Somatório (sócios + CLT + PJ + E/B)": string;
  "Tipo de empresa": string;
  "Status operacional da empresa": string;
  Índice: string;
  "Vínculo com a incubadora": string;
  Vínculo: string;
}
